# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WeatherWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 373)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 251))
        self.groupBox.setObjectName("groupBox")
        self.weatherComboBox = QtWidgets.QComboBox(self.groupBox)
        self.weatherComboBox.setGeometry(QtCore.QRect(80, 30, 221, 21))
        self.weatherComboBox.setObjectName("weatherComboBox")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.weatherComboBox.addItem("")
        self.resultText = QtWidgets.QTextEdit(self.groupBox)
        self.resultText.setGeometry(QtCore.QRect(10, 60, 411, 181))
        self.resultText.setObjectName("resultText")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 72, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(330, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.queryBtn = QtWidgets.QPushButton(Form)
        self.queryBtn.setGeometry(QtCore.QRect(110, 280, 93, 28))
        self.queryBtn.setObjectName("queryBtn")
        self.clearBtn = QtWidgets.QPushButton(Form)
        self.clearBtn.setGeometry(QtCore.QRect(250, 280, 93, 28))
        self.clearBtn.setObjectName("clearBtn")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 231, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.clearBtn.clicked.connect(Form.clearResult)
        self.queryBtn.clicked.connect(Form.queryWeather)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "三十六小時縣市天氣預報"))
        self.weatherComboBox.setItemText(0, _translate("Form", "臺北市"))
        self.weatherComboBox.setItemText(1, _translate("Form", "新北市"))
        self.weatherComboBox.setItemText(2, _translate("Form", "基隆市"))
        self.weatherComboBox.setItemText(3, _translate("Form", "桃園市"))
        self.weatherComboBox.setItemText(4, _translate("Form", "臺中市"))
        self.weatherComboBox.setItemText(5, _translate("Form", "臺南市"))
        self.weatherComboBox.setItemText(6, _translate("Form", "高雄市"))
        self.weatherComboBox.setItemText(7, _translate("Form", "新竹縣"))
        self.weatherComboBox.setItemText(8, _translate("Form", "新竹市"))
        self.weatherComboBox.setItemText(9, _translate("Form", "苗栗縣"))
        self.weatherComboBox.setItemText(10, _translate("Form", "彰化縣"))
        self.weatherComboBox.setItemText(11, _translate("Form", "南投縣"))
        self.weatherComboBox.setItemText(12, _translate("Form", "雲林縣"))
        self.weatherComboBox.setItemText(13, _translate("Form", "嘉義縣"))
        self.weatherComboBox.setItemText(14, _translate("Form", "嘉義市"))
        self.weatherComboBox.setItemText(15, _translate("Form", "屏東縣"))
        self.weatherComboBox.setItemText(16, _translate("Form", "宜蘭縣"))
        self.weatherComboBox.setItemText(17, _translate("Form", "花蓮縣"))
        self.weatherComboBox.setItemText(18, _translate("Form", "臺東縣"))
        self.weatherComboBox.setItemText(19, _translate("Form", "澎湖縣"))
        self.weatherComboBox.setItemText(20, _translate("Form", "金門縣"))
        self.weatherComboBox.setItemText(21, _translate("Form", "連江縣"))
        self.label.setText(_translate("Form", "城市"))
        self.queryBtn.setText(_translate("Form", "查詢"))
        self.clearBtn.setText(_translate("Form", "清空"))
        self.label_2.setText(_translate("Form", "資料來源:交通部中央氣象局   製作:張皓偉"))

